### ISSUE TITLE
[Week1/송재환] 유니콘 기업 정의 공유

### ISSUE THREAD

**Issue by jaehwan2** [chsop/team4_wanted_onboarding#11]
### 유니콘 기업

* 정의: 국내에선 통상적으로 기업 가치가 1조원 이상인 *비상장 스타트업
* 시장 규모와 시장점유율, 현금 유동성, 기술 혁신성, 대표의 야망 등을 종합적으로 고려하여 기업 가치 평가

기본적인 정의와 평가 내용에 대해 공유드립니다.

**Comment by jaehwan2** [comment]
우리가 가진 정보: 월별 매출액, 월별 국민연금 납부액, 월별 직원수

시장 규모, 시장 점유율 -> 기업의 시장 정보를 알 수 없으니, 확인 불가
기술 혁신성, 대표의 야망 -> 기업 정보를 알 수 없으니, 확인 불가

현금 유동성 -> 매출 대비 인건비(고정비) 비율 확인 가능 / 여러 기준 중 하나 정도로 사용

매출 및 고정비에 대한 내용만으로 추론 가능
매출의 성장률과 직원 대비 매출 성장률, 적정 고정비(급여 한정) 사용 비율, 직원 증가율 등을 고려해 분석 가능

**Comment by hellojun12** [comment]
유니콘 기업에 관한 정의가 명확하게 정해져 있네요. 

재환님이 말씀해주신것 처럼  **기업 가치가 1조원** 이상인 기업을 대상으로 분석을 진행하면 될 것 같습니다!

그렇다면 이제 문제는 '기업 가치는 어떻게 산정할 것인가? '인거 같습니다.

검색해보니 기업 가치의 선정법은 여러가지가 있네요.

또한 위에 재환님의 말씀대로 저희가 가진 정보는 연매출액/년도/월/월별_연금보험료/월별_직원수로 한정되어 있기 때문에

한정된 자원으로 기업가치를 분석해야된다는 문제점이 있네요.. 

따라서 이에 대해 따로 이슈를 만들고 팀원님들과 아이디어를 공유하고 싶은데 어떻게 생각하시는지 궁금합니다!

**Comment by jaehwan2** [comment]
저도 준식님 의견에 동의합니다.

기업 가치라는 개념을 우리가 가진 정보로 최대한 추론하는 과제인 것 같네요.

현재 제 개인적인 생각으로는 우리가 가진 정보에서 가치를 부여할 수 있는 다양하지만 논리적인 기준을 만들고, 이 기준들을 스코어링하는 방식으로 상위 기업을 가려내는 방법이 어떨지 고민 중입니다.

또한, 유니콘 기업이라는 것은 '비상장 스타트업'이라고 명시되어 있는데 상장과 비상장을 구분해야할 필요가 있을지도 함께 고민이 됩니다.

우선은 전달받은 데이터를 EDA하고, 아이디어 역시 구체화해서 공유하도록 할게요.
다른 분들도 의견이나 이견 있으시면 편하게 공유해주세요~

**Comment by ttobaegi** [comment]
말씀하신 스코어링 하는 방법 너무 좋은 것 같아요! 
EDA 하면서 스코어링에 포함될 지표와, 어떤 식으로 가중치를 부여하면 좋을 지 생각해보면 좋을 것 같네요. 
저도 데이터 보면서 고민해보겠습니다!

그리고 비상장/상장을 자료만으로 구분이 가능할까요? 
사전적 정의대로 분석을 진행하기에는 자료에 한계가 있어보여 여쭤봅니다!
