### ISSUE TITLE
[Week1/윤준식] 기업 가치 선정법

### ISSUE THREAD

**Issue by hellojun12** [chsop/team4_wanted_onboarding#13]
### 기업 가치 선정법에 관한 의견 공유
-------

**기업 가치 평가 방법**에 관해 의견을 공유해주셨으면 합니다.

※ 저희가 가진 데이터와 연관이 있으면 더 좋을거 같습니다! (제 의견입니다)
※ 아니여도 필요한 정보라 생각되면 공유해주세요!

**Comment by fhsi1** [comment]
`월별_직원수` 데이터와 `연매출액` 데이터*를 활용해서,
직원수를 많이 늘린 기업과 연매출과의 연관성을 분석해보는 것도 좋을 것 같아요.

일반적으로 매출액은 기업의 성과를 보여주는 지표 중의 하나인데,
매출액이라는 게 온전히 기업의 수익이 아니라는 점이 좀 걸리는 상황이니깐요..

매출액을 기준으로 쓸 수 있는 방법이 뭐가 있을까 고민해봤는데,
직원수 데이터를 같이 비교해보면 어떨까 하는 생각이 들어서요.!
성장속도에 맞춰 직원수가 뒷받침되어야해서 직원을 많이 뽑아야 했을테니까요.
(연금 보험료 데이터도 활용하면 좋을 것 같은데.. 아직 아이디어가 없어요 ㅠ)

직원 수 데이터와 같은 양상을 보인다면.. 
근거데이터로 사용할 수 있지 않을까 하는 개인적인 생각입니다..!

**Comment by hwangnakjoo** [comment]
개인적으로는 기업 평가 방법으로 `기업의 월별 임금 상승률`을 살펴보고 있습니다.
`월별 연금 보험료 / 월별 직원수`로 `월별 평균 보험료 납부액`을 구하고, 지난달에 비해 몇 % 증가 또는 감소했는지 그 퍼센테이지를 구한 값이 `기업의 월별 임금 상승률`이 될 수 있다고 생각합니다.

퍼센테이지 증가값이 상위 10%인 경우를 많이 포함하는 기업을 먼저 살펴봤는데,
좀더 데이터를 보는 시간이 필요한 것 같습니다. 이런 기업들이 대부분 직원 수도 적고, 월별 임금 상승률의 높낮이가 크더라구요. 보너스를 많이 받아서 그런지는 잘 모르겠습니다.. 내일 진행을 더 해보겠습니다.

**Comment by kang1471** [comment]
현재 연금 보험료 산정 기준은 매월 소득에 9%로 고용주, 노동자 반반 4.5% 부담하고 있습니다. 양적으로 직원 수가 늘어나면 월별 연금 보험료 상승이 당연하나 직원 수 증가 비해 연금 보험료 상승폭이 높으면 고액 연봉자가 들어왔음을 예상할 수 있을 것 같습니다. 

 재환님이 보내주신 자료 참고해보면 의료•바이오를 제외한 서비스와 게임 등을 제공하는 업체 모두 디지털화 되어진 플랫폼 기업들인 것 같습니다. 유니콘 기업 대부분 개발자를 많이 필요할 것을 예상할 수 있습니다.
 기업이 성장하는데 여러 분야의 직원이 필요하겠지만 개발직군의 연봉이 높다는 근거를 바탕으로(명시적 자료 필요) 직원 수 증가수 대비 월별 연금 보험료 상승폭을 살펴보면 고액 연봉자를 유치하는 기업을 추려낼 수 있지 않을까 생각하고 고액 연봉자를 유치하는 기업이 유니콘 기업이 아닐지 아이디어 제안드립니다 😊

**Comment by hellojun12** [comment]
우리나라 유니콘 기업에 대해서 공유하겠습니다.

현재 많은 팀원분들이 EDA를 해주시고 있어서 다른 방향으로 기업가치 선정에 대해 자료검색을 해봤습니다.

해당 동기는 저희가 활용하는 자료가 '실제 데이터'라는점에 기반하였고,

역으로 '우리나라 유니콘 기업'에 대해 먼저 조사하면 데이터 파악에 도움이 될 것 같아서 하게 되었습니다. 

**[우리나라 유니콘 기업]** **(클릭하면 잘보입니다!)**
![unicorn](https://user-images.githubusercontent.com/68729955/116896369-23fc0b80-ac6f-11eb-9b5f-350529eccf38.PNG)
**출처:** catch기업정보, 사람인, 잡코리아, 중기부

기업 조사를 하고 얻은 정보는 다음과 같습니다.

1. 에이프로젠을 제외한 기업의 매출액은 등재시점 **1000억원 이상, 2조 이하**이다.
2. 기업모두 등재 시점 전후로 눈에 띄는 매출액 성장이 있다. 
 
    예)크래프톤 2017년도 매출액 273억 -> 2018년도 1조 1000억원
         비바리퍼블리카 2017년도 매출액 205억 -> 2018년도 548억 -> 2019 1100억원

개인적으로 **매출액 절대량**과 매**출액 상승폭**이 제일 중요한 지표지 않을까 합니다.
2015 ~ 2019년 사이 매출액 절대량이 높아도 성장폭이 없다면 유니콘 기업이 아닐 확률이 높습니다.
또한 성장폭이 높아도 매출액이 1000억 이하면 유니콘 기업이 아닐 확률이 높죠.

이를 기반으로 첫번째 필터링을 진행하는건 어떤지 의견을 공유해 주시면 감사하겠습니다.

**Comment by chsop** [comment]
기존에 유니콘 등재된 기업 정보를 보고 기준을 어떻게 세울지 힌트 얻으면 좋겠다고 생각했는데, 준식님이 꼼꼼하게 정리해주셨네요~ 감사합니다! 말씀 해주신대로 연매출액 1000억원을 기준으로 1차 선별하는 방법 좋을것 같습니다. 그렇게 하면 5000개사 -> 103개사로 추려지네요!

그 이후에 유진, 낙주, 성규님이 말씀 해주신대로 직원수 증가율, 연금보험료 상승율, 직원수 증가율 대비 연금보험료(혹은 이를 기반으로 계산한 총지급 급여액) 상승률이 높은 기업을 확인해보면 좋을것 같아요. 저도 얼른 EDA해서 공유하겠습니다~

**Comment by chsop** [comment]
![image](https://user-images.githubusercontent.com/74705022/117033497-61c76580-ad3d-11eb-9b24-03e7d679637f.png)
http://www.investchosun.com/2019/09/18/3241646
기업가치 산정 관련 참고할만한 기사 공유합니다~
