### ISSUE TITLE
[Week1/강성규] ipynb 파일 업로드 시, JSON 형태로 보이는 현상 

### ISSUE THREAD

**Issue by kang1471** [chsop/team4_wanted_onboarding#17]
## ⁉️Pull request 시, ipynb 파일이 다음과 같이 보입니다.
![example4](https://user-images.githubusercontent.com/83483641/116816598-8be22180-ab9d-11eb-8eb5-8799211a42b3.png)
---

## jupyter note과 같이 보기 위한 방법
1. pull request 클릭
![example1](https://user-images.githubusercontent.com/83483641/116816748-293d5580-ab9e-11eb-901e-7aba3a9bff79.png)

2. 
![example2](https://user-images.githubusercontent.com/83483641/116816753-2e9aa000-ab9e-11eb-9923-c929d705b762.png)
3. 
![example3](https://user-images.githubusercontent.com/83483641/116816757-33f7ea80-ab9e-11eb-8e33-0d2067a9c6e3.png)

4. 다음과 같이 보실 수 있습니다.
![example5](https://user-images.githubusercontent.com/83483641/116816831-8df8b000-ab9e-11eb-9e32-179f87c9b8d6.png)
---

## Q. git에 ipynb 업로드 해보셨던 분들은 어떻게 대처하셨는지 궁금합니다! 
(이렇게 되어 있으면 코드에 코멘트 해주기가 어려울 것 같네요 ㅠㅠ)

**Comment by chsop** [comment]
원래 pull requests를 ipynb파일로 하면 json 형태로 보이나봐요 ㅠㅠ
아래 페북글 참고해서 ReviewNB라는 툴 설치했더니 원하는 코드 위치에 코멘트를 다는 것이 가능한데, ReviewNB가 설치되어있는 상태여야 그렇게 보이네요.
저희는 계속 ipynb 파일로 작업할 예정이니까 ReviewNB 활용해봐도 좋을 것 같습니다.  ReviewNB 페이지에서 free 버전으로 signup 하면 되고, 아래 링크 참고해서 진행하시다가 막히는 부분 있으시면 알려주세요!

https://en-gb.facebook.com/groups/TensorFlowKR/posts/1125959664411757/
