### ISSUE TITLE
[Week1/황낙주] 개인 디렉토리를 만들었습니다.

### ISSUE THREAD

**Issue by hwangnakjoo** [chsop/team4_wanted_onboarding#18]
회의 때 말씀드린 대로 각자 코드 관리가 쉽게 개인 디렉토리를 만들어 보았습니다. 
불러서 쓰는 법은 아래와 같이 해주시면 됩니다.

0. 새 폴더를 만들고 git bash 경로를 맞춰줍니다.
1. git clone https://github.com/chsop/team4_wanted_onboarding.git 
2. cd team4_wanted_onboarding/
3. git remote rm origin
4. git remote add origin https://본인깃헙링크.git
5. git pull origin main
6. 개인 디렉토리 외 다른 문서들은 다 지우고 코드나 기타 개인 자료 관리하면 될 것 같습니다. 

개인 코드를 관리하기 쉽고 push 충돌 줄일 수 있을 것 같아서 해봤는데, 괜찮은 방법일지 모르겠습니다.
week1, week2 등으로 나누려고도 생각해봤는데, 나중에 push나 pull할 때 충돌 이슈가 많이 생길 것 같아서 공통 작업용 디렉토리는 만들지 못했습니다.
현역에 계시거나 깃헙 많이 쓰시는 분들이 보시기에는 어떠신가요? 의견 부탁드립니다!

**Comment by chsop** [comment]
저도 현업에서 써본적이 없어서 어떤 방식이 더 효율적일지 모르겠지만, 풀리퀘할 개인 분석 파일이 프로젝트당 1~2개 정도라고 하면 그냥 파일명에 각자 이름을 넣어서 충돌을 피하는 방법도 있지 않을까 하는 생각이 듭니다.

사실 깃헙에서의 워크프로세스를 제대로 이해하고 있는게 맞는지부터가 좀 헷갈려서 정리 해봤는데 아래 순서로 진행하는게 맞는지도 확인 부탁드려요! 참고한 링크도 함께 공유드립니다.
https://milooy.wordpress.com/2017/06/21/working-together-with-github-tutorial/

1. 각자 EDA한 파일 풀리퀘
2. 서로 리뷰 후 merge (파일 통합 x, repo에 각자의 파일이 등록되는 개념)
3. 추가회의 후 각자 분석한 최종파일 풀리퀘
4. 서로 리뷰 후 merge (파일 통합 x, repo에 각자의 파일이 등록되는 개념)
5. 각자의 코드에서 중요한 부분들 취합해서 통합본 생성 (한명이 담당해서 해야하는 작업)
-- 여기서부터 파일이 하나로 통합되므로 버전 충돌의 가능성 생김 --
6. 충돌 주의하면서 각자 보완할수 있는 부분들 업뎃하여 최종 코드 완성 (이 부분도 다같이 의견 나눈 후에 한 사람이 맡아서 완성하는게 효과적일 것 같기도 하네요..!)

**Comment by hwangnakjoo** [comment]
좋은 링크 감사합니다. 계속 보면서 깃헙 환경을 더 배워야 될 것 같아요

그럼 이미.. 바뀐건 어떡하죠..? 제가 부탁드려서 덜컥 머지 해주셨는데..

**Comment by jaehwan2** [comment]
저는 낙주님이 알려주신대로 진행하다가 어디인지는 모르겠지만, 경로가 꼬여서 우선은 수업시간에 배운대로 다시 진행했습니다 ㅜ 미팅때 도움 좀 부탁드릴게요..

**Comment by hwangnakjoo** [comment]
윽 어쩌죠.. 제 노트북으로 최대한 해보고 적어드린건데..
제가 망친 건 아니길 바랍니다ㅠ
