### ISSUE TITLE
[Week1/송재환] 유니콘 기업분석 가설 및 분석방법 제안

### ISSUE THREAD

**Issue by jaehwan2** [chsop/team4_wanted_onboarding#21]
주어진 국민연금 데이터를 활용해 유니콘 기업을 선정할 수 있는<br>가설 및 분석방법을 제안합니다.
-------------
**제안하는 가설**은 아래와 같습니다.

1. 2019년 기준 연매출액이 1,000억원을 초과하는 기업 중
2. 전년대비 연매출액 성장률이 급등한 기업이면서,
3. 2019년 기준 월별 연금보험료 중위값이 전년대비 높은 상승률을 보인 기업이고,
4. 2019년 기준 1인당 매출액이 가장 큰 기업이 유니콘 기업일 것이다.

가설의 **근거**는 아래와 같습니다.

1. 대한민국 유니콘 기업의 등재 시점을 기준 당시 연매출액은 1,000억원 이상이다. (에이프로젠 제약 제외)<br>우리는 주어진 데이터의 최신 연도인 2019년 기준으로 분석을 실시, 유니콘 기업을 선정한다.
2. 매출 급성장은 유니콘 기업 선정의 중요 조건이다.<br>그 이유는 매출 급성장의 의미는 투자자로부터 비즈니스를 인정받아 큰 투자를 받았거나,<br>비즈니스 모델이 성공적으로 자리 잡았거나, 시장이 해당 기업을 원한다는 의미로 볼 수 있기 때문이다.<br>따라서 전년 대비 매출 급성장을 유니콘 기업 선정의 주요 조건으로 설정한다.
3. EDA 결과 일정 규모 이상의 연매출액이 발생하는 기업들은<br>직원수가 많아질수록 월별 연금 보험료가 자연스럽게 증가한다.<br>월별 연금보험료의 상승은 단순하게 회사의 전체적인 연봉 테이블이 넓어졌다는 것으로도 해석할 수 있다.<br>따라서 전체적인 직원 연봉 상승의 질을 확인하기 위해<br>2019년 월별 연금보험료의 중위값을 기준으로 전년 대비 상승률을 확인한다.
4. 1인당 매출액은 기업이 내부의 리소스를 얼마나 효과적으로 쓰는지 보여주는 지표로 볼 수 있다.<br>2번과 3번 조건이 동일하다면, 더 효과적으로 리소스를 사용하는 기업에 더 높이 평가한다.
-------------
제안하는 **분석방법**은 아래와 같습니다.

1. 2019년 연매출액이 1,000억원이 초과하는 기업으로 DF 필터링
2. 전년대비 연매출액 성장률과 전년대비 월별 연금보혐료 중위값 상승률을 기준으로 클러스터링 진행<br>계층적 군집분석 방법(https://todayisbetterthanyesterday.tistory.com/61?category=821465)
3. 상위 클러스터 중 1인당 매출액이 가장 높은 5개 기업 선정

1번 필터링만으로도 기업수가 많이 줄어들어서 클러스터링을 분석방법으로 제안하는 게 맞는지 모르겠지만,
우선은 더 정확한 분류를 통해 기업 선정하는 게 좋을 것 같아 위와 같이 제안해보았습니다.

제안한 내용에 대한 의견이나 이견 있으시면 편하게 피드백 주시기 바랍니다!

**Comment by fhsi1** [comment]
분석 기법에 대해서는 잘 몰랐었는데,
분석 기법과 더불어 그 근거까지 정리해주셔서 감사합니다!😀

말씀해주신 군집분석의 전제조건이, 이번 과제에 적합한 것 같다고 생각됩니다!
1번 필터링만으로도 기업의 수가 많이 줄어든다고 하셔서,
약식으로나마 한 번 1번 과정을 수행해 보았는데, 나쁘지 않은 것 같아요!👍
