### ISSUE TITLE
[Week2/윤준식]2021-05-10 회의록

### ISSUE THREAD

**Issue by hellojun12** [chsop/team4_wanted_onboarding#54]
### 이상치 처리

```
 - 7800건 넘게 결재한 사람은 제거
 - join_date이 1970-01-01인 데이터 --> join_date 컬럼 정보를 사용한다면 해당 데이터 제거
```

### 예측 모델

```
 - 현제 데이터의 종속변수가 한쪽으로 치우쳐져 있어 상관관계를 보는게 의미가 없다.
 - 데이터 셋의 변수가 대부분 범주형이므로 랜덤포레스트를 사용(혹은 다른 regressor)
 - 범주형 변수는 원핫인코딩/라벨인코딩 중 하나
```

### 동의된 피쳐
```
- Weekdays/holiday
- d_type
- store_id
- AD1
- retention
- join_date
- 교통량
- 강수량
- 기온(최고/최저)
- 적설량
- goods_type
```
</br>

### 이상치 처리
```
- 1일 결제 건수가 n건이 넘는다면, 어떠한 기준을 잡고 이상치를 처리해야 하는가?
- 월별 이용자수 변화와 코로나에 대한 관련성 --> 예측시 코로나 유행여부를 활용할 수 있을까?
```
### 유저 분석
```
- 유저별 리텐션을 2020-1월을 기준을 계산해서 활용해보는 것은 어떨까?
- join_date는 몇개월차 유저인지 파악하여 변수로 활용할 수 있을까?
```

### 기타 변수 관련 논의
```
- d_type: 결제수단? or 주차장 타입?
- goods_type: B가 7일 주기로 떨어지므로, A~D가 각각 공유/제휴, 주간/심야가 아닐까?
- AD1는 서울시에 국한된 데이터인가?(날씨, 교통량을 서울 데이터만 줌) or 전국구 데이터인가?
   --> 현실적으로 주어진 데이터만 가지고 판단 힘듬
```

### 예측을 위한 데이터셋 전처리
```
- 유저별&월별로 groupby한 데이터셋을 예측모델에 사용하는 경우 범주형 데이터를 어떻게
  합칠지 고민 필요(최빈값으로 진행시 두개 이상 변수가 동일한 횟수로 집계된다면?)

- 주어진 데이터셋을 row단위로 예측한다면 count 값을 예측하는 변수로 쓸수 있는 변수가 
  달라질 수 있음(user_id, join_date를 제외한 나머지 정보는 결제와 동시에 확정되는 값)
```
</br>

## 각자 해봐야 할것

```
- 주중 / 주말 + 공유일 여부 피쳐로 활용해보기
- 교통량, 기상정보 분석해보기 ( ~5/11 회의때 내용 공유)
```

**Comment by hwangnakjoo** [comment]
준식님 고생하십니다! 
정리된 내용 중에 위에서부터 몇 가지 내용 남겨요.

1. label encoding 쓰시면 될 것 같습니다.
저희가 ad1 변수도 가져가려고 하는데 one hot encoding 쓰면 갑자기 변수가 85개 더 생겨버려서 비효율적이고 모델 성능에도 영향이 갈 것 같습니다.. 그리고 제가 회의  때 문자형 변환 안 해도 되지 않냐며 혼선을 드렸는데.. 제가 배웠던 코드 다시보니 label encoding 썼네요. 죄송합니다.. 문자는 무조건 치환 필요하고, bool형이 안 써도 되는 거였네요. 제가 이렇게 기억력이 짧습니다.

2. d_type은 결제 수단 같습니다.
회의 때 찬서님이랑 준식님이 EDA 코드랑 같이 의견내실 때 d_type이 store_id에 대응되는 것 같다고 하셔서 저도 다시 살펴봤는데요. d_type은 store_id와 다대다 매칭이고 user_id와 일대일 매칭됩니다. 꼭 한 유저가 하나의 결제 수단을 이용하리라는 보장은 없지만, store_id와 대응은 다대다라 주차장 정보는 아닌 것 같아요. 결제 수단 또한 아닐 수도 있겠지만.. 제가 데이터 보고 해석한 결과는 이러합니다. 의견 더 남겨주세요! 없으시다면 저랑 준식님 1:0 ㅋㅋ

3. goods_type 카테고리 값을 보기 깔끔하게 표로 정리하겠습니다.

|value|description|
|:---:|:---:|
|A|모든 종류의 평일 주간 주차권|
|B|모든 종류의 평일 야간 주차권|
|C|모든 종류의 주말 주간 주차권|
|D|모든 종류의 주말 야간 주차권|

이것도 다른 의견 있으시면 남겨주세요. 감사합니다.

**Comment by hellojun12** [comment]
@hwangnakjoo 
제가 진거 같습니다. store_id와 다대다 매칭이라면 주차장 정보가 아니라는건 확실하네요!

**Comment by chsop** [comment]
저까지 해서 낙주님이 2점 획득하셨습니다 (2:0:0) ㅋㅋㅋ 인코딩 관련 내용도 아래 공유합니다~

라벨인코딩 (출처 : https://ysyblog.tistory.com/71)
- 숫자의 차이가 모델에 영향을 주지 않는 트리계열 모델에서 사용가능(의사결정나무, 랜덤포레스트 등)
- 숫자의 차이가 모델에 영향을 미치는 선형계열 모델에서는 사용하면 안됨(로지스틱회귀, SVM, 신경망 등)

**Comment by jaehwan2** [comment]
준식님 깔끔한 정리 감사합니다~! 

저도 어제 원핫인코딩으로 하려다 컬럼이 너무 많이 생겨서 라벨인코딩으로 진행했는데,
범주형 데이터 어떻게 처리할지 오늘 미팅에서 결정할 수 있으면 좋겠네요..ㅜ
