### ISSUE TITLE
[Week2/강성규]2021-05-10 회의 중 아이디어 정리

### ISSUE THREAD

**Issue by kang1471** [chsop/team4_wanted_onboarding#55]
# ✅ IDEA

## EDA 관련

- 작년 2, 3월 코로나 확진자 추이와 주차장 이용률과 연관이 있어 보인다. ( 동섭님 )
    - 예측 모델링 시, **코로나 추이**를 반영하면 더 정교한 모델링이 가능할 것 같다.

- 월별 이용량( 맞겠죠??.. )를 비교했을 때, **여름**이 다른 계절에 비해 더 많은 이용량을 보여준다.( 찬서님 )
    - 변화량의 추이를 확인할 때, **라인 플롯**이 극적으로 잘 보여주는 것 같다. ( 찬서님 )

- 유저별 월별 이용량 변화를 파악해보면  **유저별 리텐션**을 볼 수 있을 것이다. ( 지인님 )

- join_date 컬럼 사용 시, 몇 년차 보다는 **몇 개월 차**인지로 분석 ( 낙주님 )
    - 동질 집단으로 분류할 수도 있을 것 같다. ( 재환님 )

- d_type 컴럼 ( AA BB CC )은 **결제 수단**으로 추측된다. ( 낙주님 )
    - d_type 컴럼은 공용, 사설 과 같은 **주차장 형태**로 보여진다. ( 준식님 )

- **강수량**는 적설량이 포함된 수치이다. ( 낙주님 )

- 기상데이터 **기상 관측소가 서울이면** 서울에 한에서 적용하면 좋을 것 같다
    - 지역 정보로 추측 되는 ad_1이 **서울에 한정이 아닐 수도** 있다. ( 찬서님 )

- **교통량과 주차장 이용량** 사이 상관 관계가 있어 보인다. ( 재환님 )

---

## 모델링 관련

- 상관관계 분석을 위한 **one-hot encoding** 해야한다.

- 종속변수가 정규성을 띄어야한다. ( 낙주님 )
    - 현재 종속변수( 사용 횟수 )는 정규성을 띄지 않는다.
    - one-hot encoding을 하지 않고 그냥 넣어보자
    - 가진 변수들이 카테고리식( 분류식 ) 이산형일 때 랜덤포레스트를 사용해야함.

- one-hot이던 label 이던 성능이 뭐가 더 좋을 지는 해봐야 알 것이다. ( 찬서님 )

---

## ❗**중요**

1. row 바이로 할 것인지, 그룹 바이( 유저, 월별) → 강사님 답변 필요
2. join_date의 '*1970-01-01'* 데이터는 버리고 하자
3. 주말에 공휴일을 추가한다
4. 변수가 더 필요할 것 같다...
5. 회의 방식을 질의식으로 바꿔보자

**Comment by hellojun12** [comment]
제가 기록하면서 놓친부분이 많네요..! 추가로 기록해주셔서 감사합니다. 그리고 제가 올린 회의록도 찬서님이 많이 도와주셔서 가능했습니다! 찬서님께도 감사드려요.

**Comment by chsop** [comment]
성규님, 준식님 꼼꼼한 기록 감사드립니다!! 이렇게 서로 크로스체크 하니까 중요하게 논의했던 내용들을 확실히 짚고 갈수 있어서 좋네요:)

- 월별 이용량( 맞겠죠??.. )를 비교했을 때, 여름이 다른 계절에 비해 더 많은 이용량을 보여준다.
  -> join_date 컬럼의 월별 분포가 여름에 더 많아서 언급했던건데, 이 정보가 의미가 있으려면 가입시점과 사용시점이 일치한다는 가정이 추가로 필요할 것 같습니다. (그런데 저희 데이터만 가지고 가입후에 바로 사용했는지를 알수가 없으니 큰 의미가 없는 정보일것 같아요 ㅜㅜㅋㅋ)
  -> date 컬럼의 월별 분포가 상승세로 가다가 8,9,12월에 줄어든점이 오히려 월별 이용량 관련해서는 더 특기할만한 부분인 것 같습니다.

- 변화량의 추이를 확인할 때, 라인 플롯이 극적으로 잘 보여주는 것 같다. 
  -> 오히려 작은 변화를 극적으로 보여주는것 같아서 barplot과 같이 보면 좋을것 같다는 취지로 말씀드린 부분이었어요..! ㅎㅎ

- d_type : 슬랙에도 남겼는데 제가 ad1~d_type 관계 데이터를 잘못봤어요... 혼란을 드려 죄송합니다 ㅠㅠ~~

**Comment by jaehwan2** [comment]
성규님의 꼼꼼한 정리 감사합니다! 어제 변수중 동섭님이 말씀하신 코로나 추이 정보도 추가한다는 걸 잊었네요 ㅜ 전달주신 내용 다시 한번 살펴보면서 오늘 분석 진행하도록 하겠습니다!
