### ISSUE TITLE
[Week2/김동섭] 날씨 피처 전체 활용하는 경우 vs 날씨 피처 중 일부만 활용하는 경우

### ISSUE THREAD

**Issue by Aliasss** [chsop/team4_wanted_onboarding#68]
어제 말씀드린 것처럼 이후 일정이 있어서,, 현재까지 진행한 내용 verson 0.3 풀리퀘했습니다.

<어제 이후 현재까지 진행한 내용>
(1) 랜덤포레스트 features importance 통해 변수 중요도 파악
(2) 날씨 관련 피처, EDA 통해 제거할 피처 선정(확신이 있는 단계는 아니지만, 날씨 관련 피처 간 상관관계가 높은 것들이 있어서 제거할 필요가 있을 것으로 생각했습니다.) 
(3) 날씨 관련 피처들 제거 전 데이터셋으로 모델링 vs 날씨 관련 피처들 제거 후 데이터셋으로 모델링

[결과] : 날씨 관련 피처 중 **불쾌지수**와 **일 강수량총합**만 남긴 경우가 날씨 관련 피처 전부 제거하지 않은 경우보다 결과는 더 좋았습니다.

<날씨 관련 피처 제거 전 결과>
![image](https://user-images.githubusercontent.com/36439697/117947935-9fcf1580-b34b-11eb-8321-fe1ef71afaf2.png)

<날씨 피처 중 불쾌지수와 일 강수량총합 피처만 남기고 트레이닝한 결과>
![image](https://user-images.githubusercontent.com/36439697/117948330-00f6e900-b34c-11eb-8214-696db68e36a1.png)

**Comment by chsop** [comment]
역시 의미있는 변수만 추려서 넣는게 중요하군요...! 공유해주셔서 감사합니다~!
