### ISSUE TITLE
[Week2/황낙주] 5.12 양진호 선생님께 받은 답변 내용 정리

### ISSUE THREAD

**Issue by hwangnakjoo** [chsop/team4_wanted_onboarding#69]
- 오늘 개인적으로 양진호 선생님께 질문드린거 답변 받았는데 공유가 필요할 거 같아서 이슈로 남깁니다.

1
>Q) 월마트 예제에서 categorical 변수의 특징, 즉 ordinal 또는 nominal한지에 따라 label 부여 방법이 다르다고 나와 있는데, 랜덤포레스트의 경우 이런 label encoding에 대해서 구분이 없지 않나요? 예를 들면, 월마트 예제에서 A > B > C 순으로 판매량이 많아서 A = 3, B = 2, C = 1로 넣었지만, 만약 이런 과정 없이 label encoding하면 A = 0, B = 1, C = 2가 되는데, 이 두 과정으로 얻을 수 있는 결과의 차이가 뭔지 궁금합니다.
>
>제가 seed풀고 예제로 주신 ordinal 코드랑 sklearn labelencoder로 fit_transform 돌린 nominal 코드랑 비교해봤는데 결과가 아래처럼 나옵니다. 예제를 따라가면 ordinal이 더 좋거나 아님 큰 차이가 없거나 둘 중 하나여야 될 것 같은데, label encoding 값이 더 좋게 나와서 더 헷갈리는 것 같습니다.
>
>각각 3번씩 돌려서 얻은 WMAE 값
>ordinal(예제 코드) : 1550 / 1555.25 / 1561.52
>nominal(labelencoder) : 1536.89 / 1525.91 / 1534.44

A) ordinal 한 형태가 random forest가 판단하는데 도움이 될 것이라고 생각해서 그렇게 encoding 해주는 건데요. label encoding 방식이 더 잘나왔다면 random forest가 해당 정보를 ordinal로 판단하도록 넣어주는지 label encoding으로 넣어 주는지에 따라 **큰 차이가 없다**고 생각하시면 될 것 같습니다.

2
>Q) EDA하면서 corrplot 그려볼 때 count == 1인 값을 빼고도 그려보라고 하셨잖아요? 그럼 count == 1 데이터를 포함한 상관 분석이 A이고, 포함하지 않은게 B라고 할 때, B의 결과 값을 A에 적용해도 무리가 없나요?
>B에서 count가 어떤 x와의 양의 상관관계에 있으면 A에서는 계수가 0이어도 전체 데이터에 대해서는 'x가 count를 높이는 요인이다' 라고 말할 수 있는 건가요?

A) B와 A의 분포가 동일한 경우에 그렇게 말할 수 있습니다.

3
>Q) 저희가 가입된 지 얼마나 오래된 유저인지 알 수 있는 `howlonguser` feature를 만들었습니다. 이 변수가 기본 corrplot에서는 `user_id`와의 상관관계가 -1에 완전 근접했습니다.  `user_id`는 가입한 날짜에 따라 부여하기 때문에 `user_id`의 숫자가 높을 수록 `howlonguser`의 값이 낮은 것을 확인했습니다. 이 경우 `howlonguser`를 제거해도 괜찮은 게 맞나요?

A) 해당 형태라면 `howlonguser`에서 얻을 수 있는 정보가 `user_id`에 모두 담겨있을 것 같아서 굳이 `howlonguser`라는 feature를 추가하는게 ML 모델링 관점에서는 의미가 없을 것 같습니다. 하지만 EDA 등 분석할 때는 유용할 수도 있겠네요. 꼭 유의미한 결과가 안나와도 **그룹핑을 하고 분석한 내용이 있다면 비즈니스적 의사결정 하는데 많은 도움이 될 것** 같아서 유용할 것 같네요.

<br>

- 답변 정리한 건 이렇구요. 답변 내용 중에 크게 중요하다고 생각하는 2 가지만 따로 정리해서 말씀드리면 이렇습니다.<br><br>

1. label encoding 할 때 월마트 예제에서의 구분처럼 ordinal / nominal 따로 신경쓰지 않으셔도 될 것 같습니다.
2. 지인님께서 진행하신 user_id별 누적 카운트 계산하신 것도 여쭤봤는데, 그렇게 그룹핑한 컬럼을 EDA로 활용하는 건 비즈니스적으로 아주 좋은 접근이라고 하셨습니다. 무조건 써야 될 것 같아요. 모델링 말고 EDA를 통해 볼 수 있는 비즈니스적인 아이디어를 많이 도출해야 될 것 같아요. 저도 howlonguser를 지우지 않고 찬서님 의견처럼 뭐 브실골플 등급으로 나눠서 더 EDA 진행해보겠습니다. 제가 join_date는 지워도 될 것 같다고 했는데, ML 관점에서만 그렇고 EDA 단계에서는 필요한 것 같습니다. 따라서 join_date == '1970-01-01' 데이터만 지울게요.

**Comment by ttobaegi** [comment]
낙주님 공유 감사합니다! 
2. 저도 user_id 별 누적 카운트 부분 클래스 나눠서 좀 더 살펴보고 공유드리겠습니다!

**Comment by jaehwan2** [comment]
낙주님 선생님 답변 공유 감사합니다.
낙주님이 공유주신 내용 참고해서 분석해보겠습니다.
계획보다 진도가 나가지 않아서 완성도는 많이 떨어지네요 ㅜ

**Comment by chsop** [comment]
오오 분석 방향성 잡는데 도움이 많이 되는 내용들이네요! 질문 해주시고 답변 공유해주셔서 감사합니다~! 브실골플이 뭔지 잠시 고민했네요...ㅎㅎㅎ
