### ISSUE TITLE
[Week2/이지인] 유저 이용횟수 클래스별 추가 분석 내용 공유 건

### ISSUE THREAD

**Issue by ttobaegi** [chsop/team4_wanted_onboarding#71]
- 999665 이상치 제외

낙주님 말씀 참고하여, freq_cum 기준으로 4 개 클래스로 분류해서 파악했습니다.
![image](https://user-images.githubusercontent.com/79742748/118063336-dea8ae00-b3d3-11eb-8088-ba518da66c64.png)

 **요일별/goods_type/d_type** 
- 클래스별로 집계는 유저별 편차가 커 mean 대신에 sum 으로 했습니다. 

![image](https://user-images.githubusercontent.com/79742748/118012073-a54c5000-b38b-11eb-9b9c-6134c2b16037.png)
-요일별 결제 건수 합계
> - 클래스 1 : 평일 대비 토요일 결제 건수 급증
> - 클래스 3, 4 : 평일 결제 건수 집중 

![image](https://user-images.githubusercontent.com/79742748/118012387-f3615380-b38b-11eb-9868-04113c96e16b.png)
- d_type 클래스별 차이 없어보임

![image](https://user-images.githubusercontent.com/79742748/118068113-c5582f80-b3dc-11eb-9115-fd12f5943631.png)
- goods_type 
> - D :클래스 1 에 주로 분포 
> - 클래스별(1→2→3→4)로 goods_type 분포가 조금씩 달라짐 : 클래스 1 평일 A>B>C, 주말 A>C>B / 클래스 4 평일, 주말 A>C>B 인 경향

아직 해석을 자세하게하지 못했는데, 확실히 보이는 부분만 전달드립니다! 추가 코멘트해주시면 좋을 것 같습니다!

**Comment by chsop** [comment]
공유 감사합니다 지인님~!! 이렇게 구분해서 보니까 클래스 1과 4의 good_type 차이가 확실히 보이네요..! 혹시 클래스는 freq_cum 기준으로 1/4씩 나누셨나요?

**Comment by ttobaegi** [comment]
4분위 수 기준으로 나눴는데, 혹시 더 좋은 방법이 있을까요? ㅠ ㅠ
![image](https://user-images.githubusercontent.com/79742748/118105677-a62ac380-b417-11eb-83d9-4faa6a7da792.png)

**Comment by chsop** [comment]
저도 고민하다가 임의의 기준을 적용하긴 했는데, 아무래도 1회만 이용한 유저 비중이 높으니 누적 이용횟수(1회는 a등급, 2~10회는 b등급, 11~50회는 c등급...)를 기준으로 나눠보는 것도 방법이 될수 있지 않을까 싶어요...!
