### ISSUE TITLE
[Week3/송재환] 클로젯셰어 제품별 태그 및 가격 정보 공유

### ISSUE THREAD

**Issue by jaehwan2** [chsop/team4_wanted_onboarding#81]
어제 클로젯셰어 사이트를 검색해보니, 과제로 받은 제품명이 검색이 되더라구요.
그래서 크롤링하여 제품별 태그 및 가격 정보 구해봤습니다.
다만, 모든 정보가 있는 게 아니라 활용 방향에 대해서는 논의할 필요가 있을 것 같습니다.
어제 제가 이렇게저렇게 해보다가 크롤링 코드가 더러워져서, 정리한 다음에 코드도 공유드리겠습니다.

[tag_price_df.xlsx](https://github.com/chsop/team4_wanted_onboarding/files/6488388/tag_price_df.xlsx)

**Comment by ttobaegi** [comment]
우와 벌써크롤링까지.. 이거 활용하면 이번에는 RFM도 적용해볼 수 있겠네요! 감사합니다!!

**Comment by chsop** [comment]
오오 대단하십니다! 가격정보가 같이 있으면 훨씬 좋겠네요~~
