### ISSUE TITLE
[Week1/조유진] 2021-05-02 회의록

### ISSUE THREAD

**Issue by fhsi1** [chsop/team4_wanted_onboarding#9]
## ✅ Week schedule

⚠️ **2021.05.04(화) 오후 9시 Meeting**

: 유니콘 기업에 대해 조사 후, 공유 및 방향성 고민

## ‼️ Task

- 유니콘 기업이 무엇인가?
- 어떻게 유니콘 기업을 찾을 수 있는가? (과제)
- (Post) 유니콘 기업의 특성은 무엇인가?
- 그러한 특징을 가진 회사는 무엇인가?
- 분석한 내용을 어떻게 활용할 수 있을까?

## ✅ Issue LABEL
|LABEL |NAME ex.|
|----------------|-------------------------------|
|`IDEA`|[Week1/이름] 유니콘 기업분석 접근방향 아이디어|
|`INFO`|[Week1/이름] 유니콘 기업분석 배경지식|
|`CODE`|[Week1/이름] 유니콘 기업분석 피드백 요청 v0.1|-- is en-dash, --- is em-dash|
|`QUESTION`|[Week1/이름] 유니콘 기업분석 코드질문|
|`ETC`|[Week1/이름] 자유양식|

## ✅ .ipynb 이름 형식

`[NAME]`_onboarding_week1_analysis_v0.1.ipynb

## ✅ Issue 이름 형식

```
[Week1/이름] 유니콘 기업분석 접근방향 아이디어
[Week1/이름] 유니콘 기업분석 배경지식
[Week1/이름] 유니콘 기업분석 피드백 요청 v0.1
[Week1/이름] 유니콘 기업분석 코드질문
[Week1/이름] 자유양식
```

## ⚠️ version numbering

팀원 합의로 버전 전환

## ✅ Commit Message

`[CREATE] 작업내용`

`[UPDATE] 작업내용`

`[DELETE] 작업내용`

**Comment by kang1471** [comment]
Commit Message에 [ADD]와 [UPDATE]가 중복되는 것 같아서 새로운 파일에 대해서는 [CREATE]가 좋을 것 같습니다! ㅎㅎ

**Comment by fhsi1** [comment]
수정했습니다~
